version: "3"
services:
  api:
    container_name: JDBC
    hostname: jdbc
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "pass"
      DB_HOST: "mysql"
      DB_NAME: "dropwizard"
    ports:
      - "127.0.0.1:8080:8080"
    build: .
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "dropwizard"
    ports:
      - "127.0.0.1:3306:3306"